export const ui = {
  discuss: { ru: "Связаться", en: "Contact me" },
  openDemo: { ru: "Открыть демо", en: "Open the demo" },
  openSite: { ru: "Открыть сайт", en: "Open the site" },
  demoAdmin: { ru: "Демо-админка", en: "Admin demo" },
  openDemoAdmin: { ru: "Открыть демо-админку", en: "Open the admin demo" },
  bot: { ru: "Бот в Telegram", en: "Telegram bot" },

  format: { ru: "Формат", en: "Format" },
  role: { ru: "Моя роль", en: "My role" },
  term: { ru: "Срок", en: "Timeline" },

  clientSide: { ru: "Сторона клиента", en: "Client side" },
  ownerSide: { ru: "Сторона владельца", en: "Owner side" },
  howItCounts: { ru: "Как это считает", en: "How it calculates" },
  front: { ru: "фронт", en: "front" },
  back: { ru: "бэк", en: "back" },

  stackTitle: { ru: "Что используется", en: "What it's built with" },
  frontend: { ru: "Фронтенд", en: "Frontend" },
  backend: { ru: "Бэкенд", en: "Backend" },
  frontendNote: { ru: "то, что видит клиент", en: "what the client sees" },
  backendNote: { ru: "то, что работает за экраном", en: "what runs behind the screen" },

  telegram: { ru: "Telegram", en: "Telegram" },
  email: { ru: "Почта", en: "Email" },
  nextProject: { ru: "Следующий проект", en: "Next project" },
  firstProject: { ru: "К первому проекту", en: "Back to the first project" },
  projects: { ru: "Проекты", en: "Projects" },
  about: { ru: "Главная", en: "Home" },
  hello: { ru: "Меня зовут", en: "My name is" },
  writeEmail: { ru: "Написать на почту", en: "Email me" },
  openCase: { ru: "Открыть кейс", en: "Open the case" },
  firstCase: { ru: "Первый кейс", en: "First case" },
  seeProjects: { ru: "Смотреть проекты", en: "See the projects" },
  what: { ru: "Что это", en: "What it is" },
  problem: { ru: "Задача", en: "Problem" },
  stack: { ru: "Стек", en: "Stack" },
  highlights: { ru: "Инженерия", en: "Engineering" },
  caseStudy: { ru: "Разбор проекта", en: "Case study" },
  demo: { ru: "Демо", en: "Live demo" },
  site: { ru: "Сайт", en: "Live site" },
  code: { ru: "Код на GitHub", en: "Code on GitHub" },
  apiDocs: { ru: "Документация API", en: "API docs" },
  profile: { ru: "Профиль", en: "Profile" },

  architecture: { ru: "Архитектура", en: "Architecture" },
  decisionsTitle: { ru: "Инженерные решения", en: "Engineering decisions" },
  underTheHood: { ru: "Под капотом", en: "Under the hood" },

  status: { ru: "Статус", en: "Status" },
  inDemo: { ru: "В демо", en: "In the demo" },

  mainNav: { ru: "Основная навигация", en: "Main navigation" },
  homeLink: { ru: "На главную", en: "Go to the home page" },
  skip: { ru: "Перейти к содержимому", en: "Skip to content" },
  language: { ru: "Язык", en: "Language" },

  notFound: { ru: "Такой страницы нет", en: "Page not found" },
  notFoundText: {
    ru: "Адрес не ведёт ни на одну страницу сайта. Проверьте ссылку или откройте главную.",
    en: "This address doesn't lead to any page of the site. Check the link or open the home page.",
  },
  toHome: { ru: "На главную", en: "Go to the home page" },
  toProjects: { ru: "К проектам", en: "Go to projects" },
};
